-- Roles
INSERT INTO roles (name) VALUES
    ('User'),
    ('Admin');

-- Genders
INSERT INTO genders (name) VALUES
    ('Masculino'),
    ('Feminino'),
    ('Outro');

-- Disabilities
INSERT INTO disabilities (name) VALUES
    ('Visual'),
    ('Auditiva'),
    ('Mental'),
    ('Física'),
    ('Múltipla'),
    ('Nenhuma');

-- Drivers Licenses
INSERT INTO drivers_licenses (name) VALUES
    ('A'),
    ('B'),
    ('C'),
    ('D'),
    ('E'),
    ('Nenhuma');

-- Marital Statuses
INSERT INTO marital_statuses (name) VALUES
    ('Solteiro'),
    ('Casado'),
    ('União Estável'),
    ('Divorciado'),
    ('Viúvo'),
    ('Prefiro Não Declarar');

-- Ethnicities
INSERT INTO ethnicities (name) VALUES
    ('Preto'),
    ('Pardo'),
    ('Branco'),
    ('Indígena'),
    ('Amarelo'),
    ('Prefiro Não Declarar');

-- Nationalities
INSERT INTO nationalities (name) VALUES
    ('Afegão'),
    ('Sul-Africano'),
    ('Albanês'),
    ('Alemão'),
    ('Andorrano'),
    ('Angolano'),
    ('Antiguano'),
    ('Saudita'),
    ('Argelino'),
    ('Argentino'),
    ('Armênio'),
    ('Australiano'),
    ('Austríaco'),
    ('Azerbaijano'),
    ('Bahamense'),
    ('Bangladeshiano'),
    ('Barbadiano'),
    ('Bahraini'),
    ('Belga'),
    ('Belizenho'),
    ('Beninense'),
    ('Butanês'),
    ('Boliviano'),
    ('Bosniano'),
    ('Botsuano'),
    ('Brasileiro'),
    ('Britânico'),
    ('Bruneano'),
    ('Búlgaro'),
    ('Burquinense'),
    ('Burundês'),
    ('Butanês'),
    ('Cabo-verdiano'),
    ('Cambojano'),
    ('Camaronês'),
    ('Canadense'),
    ('Centro-Africano'),
    ('Chadiano'),
    ('Chileno'),
    ('Chinês'),
    ('Chinês de Hong Kong'),
    ('Chinês de Macau'),
    ('Chipriota'),
    ('Colombiano'),
    ('Comorense'),
    ('Congo-Brazzaville'),
    ('Congo-Kinshasa'),
    ('Costarriquenho'),
    ('Croata'),
    ('Cubano'),
    ('Dinamarquês'),
    ('Djibutiense'),
    ('Dominicano'),
    ('Dominicano de Dominica'),
    ('Egípcio'),
    ('Salvadorenho'),
    ('Emiradense'),
    ('Equatoriano'),
    ('Eritreu'),
    ('Eslovaco'),
    ('Esloveno'),
    ('Espanhol'),
    ('Estadunidense'),
    ('Estoniano'),
    ('Etíope'),
    ('Fijiano'),
    ('Filipino'),
    ('Finlandês'),
    ('Francês'),
    ('Gabão'),
    ('Gambiano'),
    ('Ganaense'),
    ('Georgiano'),
    ('Grego'),
    ('Granadino'),
    ('Guatemalteco'),
    ('Guianês'),
    ('Guineense'),
    ('Guineense Equatorial'),
    ('Guineense-Bissauense'),
    ('Haitiano'),
    ('Hondurenho'),
    ('Húngaro'),
    ('Iemenita'),
    ('Indiano'),
    ('Indonésio'),
    ('Iraniano'),
    ('Iraquiano'),
    ('Irlandês'),
    ('Islandês'),
    ('Israelense'),
    ('Italiano'),
    ('Jamaicano'),
    ('Japonês'),
    ('Jordano'),
    ('Kazakhstani'),
    ('Queniano'),
    ('Kitts e Nevisense'),
    ('Kosovar'),
    ('Kuwaiti'),
    ('Kyrgystani'),
    ('Laosiano'),
    ('Letão'),
    ('Libanês'),
    ('Liberiano'),
    ('Líbio'),
    ('Liechtensteiniano'),
    ('Lituano'),
    ('Luxemburguês'),
    ('Madagascarense'),
    ('Malásio'),
    ('Malawiano'),
    ('Maldívio'),
    ('Maliano'),
    ('Maltês'),
    ('Marfinense'),
    ('Marroquino'),
    ('Mauritano'),
    ('Maurício'),
    ('Mexicano'),
    ('Micronésio'),
    ('Moldavo'),
    ('Monegasco'),
    ('Mongol'),
    ('Montenegrino'),
    ('Mozambicano'),
    ('Namibiano'),
    ('Nauruano'),
    ('Nepalês'),
    ('Neozelandês'),
    ('Nicaraguense'),
    ('Nigeriano'),
    ('Nigerino'),
    ('Norueguês'),
    ('Omã'),
    ('Paquistanês'),
    ('Palauense'),
    ('Palestino'),
    ('Panamenho'),
    ('Papua'),
    ('Paraguaio'),
    ('Peruano'),
    ('Polaco'),
    ('Português'),
    ('Qatarense'),
    ('Quirguiz'),
    ('Romeno'),
    ('Ruandês'),
    ('Russo'),
    ('Samoano'),
    ('Sanvincentino'),
    ('Sao-Tomense'),
    ('Saudita'),
    ('Senegalês'),
    ('Seri-Lanquês'),
    ('Sérvio'),
    ('Seychellense'),
    ('Sierra-Leonês'),
    ('Singapurense'),
    ('Sírio'),
    ('Somaliano'),
    ('Sotho'),
    ('Sudanês'),
    ('Sudanês do Sul'),
    ('Sueco'),
    ('Suíço'),
    ('Surinamês'),
    ('Swazi'),
    ('Tajiquistanês'),
    ('Tailandês'),
    ('Tanzaniano'),
    ('Timorense'),
    ('Togolês'),
    ('Tonganês'),
    ('Trindadense'),
    ('Tunisiano'),
    ('Turcomeno'),
    ('Turco'),
    ('Tuvaluano'),
    ('Ugandense'),
    ('Ucraniano'),
    ('Uruguaio'),
    ('Uzbeque'),
    ('Vanuatuense'),
    ('Venezuelano'),
    ('Vietnamita'),
    ('Zambiano'),
    ('Zimbabuano');

