name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify build output
        run: ls -R out/ || echo "⚠️ Diretório out/ está vazio!"

      - name: Delete ALL files from FTP (except required files)
        run: |
          if ! command -v lftp &> /dev/null; then
            sudo apt-get install -y lftp
          fi
          printf -v FTP_PASS_ESCAPED "%q" "$FTP_PASS"  # Escapa os caracteres especiais
          lftp -u ${{ secrets.FTP_USER }},$FTP_PASS_ESCAPED ${{ secrets.FTP_HOST }} <<EOF
          set ssl:verify-certificate no
          cd /domains/logumrh.com.br/public_html
          find . -mindepth 1 ! -name 'config.php' ! -name 'submit_application.php' ! -name 'test_env.php' -exec rm -rf {} + || echo "⚠️ Falha ao remover alguns arquivos!"
          bye
          EOF


      - name: Wait after delete
        run: sleep 5 # Aguarda o servidor processar a remoção dos arquivos

      - name: Upload files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: "out/"
          server-dir: "/domains/logumrh.com.br/public_html/"
          dangerous-clean-slate: true # Remove qualquer coisa no servidor antes do upload (exceto arquivos protegidos)
